version: '1.0'
name: build-and-release

triggers:
  - type: tag
    branches:
      include:
        - 'v*'

stages:
  - name: build-mac
    image: node:20
    commands:
      - cd cat-vue
      - npm install -g pnpm
      - pnpm install
      - pnpm build:mac
    artifacts:
      - cat-vue/dist/*.dmg

  - name: build-win
    image: electronuserland/builder:wine
    commands:
      - cd cat-vue
      - npm install -g pnpm
      - pnpm install
      - pnpm build:win
    artifacts:
      - cat-vue/dist/*.exe
